language: java
sudo: false
install: true
jdk:
- openjdk8
script:
- mvn clean verify sonar:sonar -Pcoverage
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: unimibsoftengcourse1920
    token:
      secure: "fP4w27RzHqnZ8KrJyTTsFLflTDFGGcRbPd838M6O6QK9mTp5rp+jv7fNWtrBJPGI1XpaHKGTnQD6BA1wZ8kc9246EFsiC2CKux8hxbWza4sRHBfbc4nunA59Frc0qjqbGgIQbJx5jVk+HV+Wm9EvRvWrjfP+oI2Ww81QxoupMKP6aRiEGYMmEH6Gpxj6dBOLbczLzjVUw6hysLi5K/xQ5rAj/ffW3NG42mcK43u+kbUkJrULya6vsUL0rhFYhgkZVVOOhi+B85KPbTEHpxcZfLC5j6WdLnYqCiw5HkLK3NDhESNm2D4SjoKP5IGnC2G1A4NjMnPVehkQMA4UWluCUkdbK/Ta0MFdqwkUw97WR0JqAv+p/LNK/x/4d2Bmqtdk/hsa1ISKI84jHAI6C6muz1OPsNubadvH5ys7Ibtc0IP75qUFdC6vpIb4+rG8Fisi16qBU7JryMe3ZELGMDkjJWAYZbbFbaxoi1SEPRmt/m8Aw4PdXOlDaEq2wf5XPRngkvyj/hvbIi+dVgXVckiiAl0EAKQDPmIFBq7Wd2GA1YZ9dExmwZ0LOyl8yYfyl16r6RVK8hYyEsGIv5k1P9ZqCHvlS8DpcPPdpFVUk6MkXsCe/5dvlaAkpWkwGAUPnKyU6vYJ58lGXuRcuuy7eQHpiwKfavAIk9JeskUbd3a9Vzc="

env:
  global:
    secure: gvSmkaE+brx9LUa1H6a4YzFUyndCK0YrjngdLItn6W2OpPempbfDsbcTakf6EjxtTR2d6HGBh0R4I0SP1SKoDEpT3cIRkuwYdgePWBU2cZq7UltoB1gzmO5FOGtg/620P7xtU9lmqMQ2eo3909nV5QZceBNwCBNe10IR/36lnku44bAoQxNJjJqImHjRl9FOi6SqW4ED0fLKEqC0OdcNk0f07q21hAGxxDNIuiTXzq7Ylni8Ar3m33qbuTN8vwMts203M/Oq9/qBBGkNOTAGnYpoY5cjpvgUHGM5gXiP+Cz02H+vxB9KdqF7SForjhyxnnq+lCJK/UilJFyOz2rB+0t3JoL/RXg5WCWvyVU01NnaVMh37L9slHN4LJNyF9SmKjmqu6NYoGwVOu/TaieS9hElXankPwn0vh1iHsQdX5c2o0o8sA9VZ5FCSrPDyyP+Mmk2vISbQnj16dFVRGM+RlY38AhjWtV+f6fMsANeFVdfiBsAXiGLFgKbQ+EXzk7i39J+5UdgOXHAjWvwqIhOkSa8QcRSc0pJAqWWeNDBubRZzvAb8LNF3FCwDHZlxGIT+dkIbGjgv9YHJRFZ3W9D899yfI2QxCP5uV+/VCVNC0fRBqH41lJiF1xuuuw6KCmJ8wrSub3XuX9FF9b8aOnfe2GTliGvJkDSiYMOcKsIf7w=
